### ISSUE TITLE
issue with unraid connection 

### ISSUE THREAD

**Issue by Shiroe93** [IDmedia/hass-unraid#12]
i'm not able to connect to unraid but mqtt works fine 
 here's te log 
```
Traceback (most recent call last):
File "/app/main.py", line 283, in <module>
UnRAIDServer(config.get('mqtt'), unraid_config)
File "/app/main.py", line 20, in __init__
unraid_host = unraid_config.get('host')
AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
File "/app/main.py", line 283, in <module>
UnRAIDServer(config.get('mqtt'), unraid_config)
File "/app/main.py", line 20, in __init__
unraid_host = unraid_config.get('host')
AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
File "/app/main.py", line 283, in <module>
UnRAIDServer(config.get('mqtt'), unraid_config)
File "/app/main.py", line 20, in __init__
unraid_host = unraid_config.get('host')
AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
File "/app/main.py", line 286, in <module>
loop.run_forever()
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
self._run_once()
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1869, in _run_once
event_list = self._selector.select(timeout)
File "/usr/local/lib/python3.9/selectors.py", line 469, in select
fd_event_list = self._selector.poll(timeout, max_ev)
File "/app/utils.py", line 29, in handle_sigterm
raise KeyboardInterrupt()
KeyboardInterrupt
Traceback (most recent call last):
File "/app/main.py", line 286, in <module>
loop.run_forever()
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
self._run_once()
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1869, in _run_once
event_list = self._selector.select(timeout)
File "/usr/local/lib/python3.9/selectors.py", line 469, in select
fd_event_list = self._selector.poll(timeout, max_ev)
File "/app/utils.py", line 29, in handle_sigterm
raise KeyboardInterrupt()
KeyboardInterrupt
Traceback (most recent call last):
File "/app/main.py", line 286, in <module>
loop.run_forever()
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
self._run_once()
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1869, in _run_once
event_list = self._selector.select(timeout)
File "/usr/local/lib/python3.9/selectors.py", line 469, in select
fd_event_list = self._selector.poll(timeout, max_ev)
File "/app/utils.py", line 29, in handle_sigterm
raise KeyboardInterrupt()
KeyboardInterrupt
2024-08-24 10:26:47,250 [INFO] [Shiroe-Tower] Connecting to mqtt server...
2024-08-24 10:26:47,255 [INFO] [Shiroe-Tower] Successfully connected to mqtt server
2024-08-24 10:26:47,257 [INFO] [Shiroe-Tower] Connecting to unraid...
2024-08-24 10:26:47,789 [ERROR] [Shiroe-Tower] Failed to connect to unraid due to a timeout or connection issue...
2024-08-24 10:27:17,793 [INFO] [Shiroe-Tower] Connecting to unraid...
```

here's the sanitize config.yaml

```
unraid:
  name: Shiroe-Tower
  host: http://192.168.50.12
  port: 80
  ssl: False
  username: ROOT USER
  password: PASS
  scan_interval: 30

mqtt:
  host: 192.168.50.46
  port: 1883
  username: USER
  password: PASS
```

**Comment by Shiroe93** [comment]
got it working

**Comment by ampersandru** [comment]
> got it working

Im having the same error - how did you fix it?

**Comment by Shiroe93** [comment]
it was a problem with text formatting i will attach the file so you can change the relevant data and upload it as it is after changing the file extension from .txt to yaml
[config.txt](https://github.com/user-attachments/files/16997490/config.txt)

**Comment by ampersandru** [comment]
thanks! that worked. I also had http:// in front of the UGREEN address before and that might have been the issue

**Comment by Shiroe93** [comment]
it is not clear if the http:// is needed or not for me it worked without it but in other issues the creator mentions is needed to distinguish betwhen ws or wss when mounting the socket
