### ISSUE TITLE
MQTT without a username and password

### ISSUE THREAD

**Issue by tonyhardcode** [IDmedia/hass-unraid#18]
My MQTT container does not have user/pass restrictions and this might be causing issues with hass-unraid.

> KeyboardInterrupt
Task was destroyed but it is pending!
task: <Task pending name='Task-1' coro=<Client._resend_qos_messages() done, defined at /usr/local/lib/python3.9/site-packages/gmqtt/client.py:176> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x14d5fc1e11c0>()]>>
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<UnRAIDServer.mqtt_connect() done, defined at /app/main.py:141> exception=AttributeError("'NoneType' object has no attribute 'encode'")>
Traceback (most recent call last):
  File "/app/main.py", line 153, in mqtt_connect
    self.mqtt_client.set_auth_credentials(mqtt_username, mqtt_password)
  File "/usr/local/lib/python3.9/site-packages/gmqtt/client.py", line 210, in set_auth_credentials
    self._username = username.encode()
AttributeError: 'NoneType' object has no attribute 'encode'

I tried leaving the MQTT username and password empty in the config as well as completely removing them. Still the same issue.

**Comment by Samo27** [comment]
I dont have username and password set on my mqtt broker. In config.yaml I just put some random text under username and password. Works like a charm.

**Comment by tim80732** [comment]
I use "anonymous" as username and left password empty.
It worked!

**Comment by IDmedia** [comment]
Based on @tim80732 I guess I can close this issue. Not tested it myself
