### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by K3vb3rt** [IDmedia/hass-unraid#20]
Hi,
would like to use this integration to replace Glances. But everytime I set up, I get 
**"TypeError: 'NoneType' object is not iterable"**
The config.yaml is in the mapped folder /mnt/user/appdata/hass-unraid/data

**My compose:**

services:
  hass-unraid:
    container_name: hass-unraid
    network_mode: bridge
    restart: always
    environment:
      - TZ=Europe/Berlin
    volumes:
      - '/mnt/user/appdata/hass-unraid/data:/data'
    labels:
      - 'net.unraid.docker.icon=/mnt/user/docker/docker-icons/data/hass-unraid.png'
    image: ghcr.io/idmedia/hass-unraid:latest

**My config.yaml:**

unraid:
  - name: Hive
    host: 192.168.1.100
    port: 80
    ssl: False
    username: root
    password: my_supersecret_password
    scan_interval: 30

  
mqtt:
  host: 192.168.1.144
  port: 1883
  username: mqtt-user
  password: my_supersecret_password

Can anyone help me to get this running?

**Comment by K3vb3rt** [comment]
Add Log:

TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/app/main.py", line 284, in <module>
    for unraid_config in config.get('unraid'):
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/app/main.py", line 284, in <module>
    for unraid_config in config.get('unraid'):
TypeError: 'NoneType' object is not iterable

**Comment by Flobenki** [comment]
Had the same Problem, for me the fix was to move the config.yaml from /hass-unraid/data/ directly in the /hass-unraid/ directory

**Comment by tony77682** [comment]
does not work for me, even in the /hass-unraid folder, the error is still there

**Comment by K3vb3rt** [comment]
+1 for me. Still does not work.

**Comment by 0xvisualiris** [comment]
+1 Can't get it to work :(

**Comment by pizza2548** [comment]
i found that when i created my config.yaml on windows it caused access issues for it, i created a new one using Krusader on Docker and it is now working.

Check your read/write access for nobody on it as mine wasn't set right and as such it wouldn't find the config file.

**Comment by IDmedia** [comment]
I recommend to run the file through a YAML validator and make sure the file is valid.
Make sure to have the same indentations as the example in the README has.

**Comment by K3vb3rt** [comment]
That did the trick for me! Thanks!
Created the config.yaml via ssh using VSS.
