### ISSUE TITLE
Cannot parse disk information

### ISSUE THREAD

**Issue by adrianipopescu** [IDmedia/hass-unraid#21]
Hi

I can't seem to get disk and share size information via mqtt.

So far what I've got in the logs is:

`2024-10-13 19:07:56,710 [INFO] [Babel] Parse data for disks
Task exception was never retrieved
future: <Task finished name='Task-34031' coro=<shares() done, defined at /app/parsers.py:60> exception=ReadTimeout('')>
Traceback (most recent call last):
    raise to_exc(exc)
httpcore.ReadTimeout
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/parsers.py", line 117, in shares
    r = await http.request("GET", url=f'{self.unraid_url}/webGui/include/ShareList.php', data=data, headers=headers, timeout=600)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1716, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout`

Any idea what I'm doing wrong?

Additional context: hosting as docker.

**Comment by IDmedia** [comment]
I need more info. What version of UnRAID are you using? Are you using SSL and is it self signed?
I can't reproduce this error. Closing for now, feel free to reopen if needed.
