### ISSUE TITLE
Invalid URI Schema

### ISSUE THREAD

**Issue by greghesp** [IDmedia/hass-unraid#25]
When firing up the container, this is the error I get.  I think it's trying to get the Cookie to login, but tries to do it via a websocket by mistake?

```
2024-12-22 12:35:54,562 [ERROR] [Raptor] Last message received:
2024-12-22 12:35:54,563 [ERROR] [Raptor] 
2024-12-22 12:36:24,565 [INFO] [Raptor] Connecting to unraid...
2024-12-22 12:36:24,624 [ERROR] [Raptor] Failed to connect to unraid due to an exception...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 658, in __await_impl__
    await protocol.handshake(
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 326, in handshake
    raise RedirectHandshake(response_headers["Location"])
websockets.exceptions.RedirectHandshake: redirect to http://192.168.1.102/login

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/main.py", line 208, in ws_connect
    async with websockets.connect(websocket_url, subprotocols=subprotocols, extra_headers=headers) as websocket:
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 633, in __aenter__
    return await self
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 650, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 668, in __await_impl__
    self.handle_redirect(exc.uri)
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 555, in handle_redirect
    new_wsuri = parse_uri(new_uri)
  File "/usr/local/lib/python3.9/site-packages/websockets/uri.py", line 77, in parse_uri
    raise exceptions.InvalidURI(uri, "scheme isn't ws or wss")
websockets.exceptions.InvalidURI: http://192.168.1.102/login isn't a valid URI: scheme isn't ws or wss
```

**Comment by jokerigno** [comment]
had same issue. For me was because of special characters in password

**Comment by reffr** [comment]
Did you have to remove the special character from your root password for unraid? Or, did you do something else? I would really not like to weaken my root pwd but also really want to get this to work. Thanks!

**Comment by IDmedia** [comment]
The original issue is solved, please don't hijack other posts. Create a new issue with enough information for me to reproduce the issue (Unraid Version, config, log etc..)

**Comment by reffr** [comment]
Thank you and my apologies.
